parameters:
  coinmarketcap.api.url: "%env(COINMARKETCAP_API_URL)%"
  coinmarketcap.api.token: "%env(COINMARKETCAP_API_TOKEN)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

doctrine:
  dbal:
    default_connection: crypto_tracker
    connections:
      crypto_tracker:
        server_version: 11
        driver: pdo_pgsql
        url: "%env(DATABASE_URL)%"
  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: crypto_tracker
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
