parameters:
  coinmarketcap.api.url: "%env(COINMARKETCAP_API_URL)%"
  coinmarketcap.api.token: "%env(COINMARKETCAP_API_TOKEN)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

doctrine:
  dbal:
    default_connection: crypto_tracker_BDD
    connections:
      crypto_tracker_BDD:
        server_version: 11
        driver: pdo_pgsql
        url: "%env(DATABASE_URL)%"
    types:
      uuid: Symfony\Bridge\Doctrine\Types\UuidType

  orm:
    default_entity_manager: postgres
    entity_managers:
      postgres:
        connection: crypto_tracker_BDD
        naming_strategy: doctrine.orm.naming_strategy.underscore
